### ISSUE TITLE
Question: Does the package work with autoform/simpleschema?

### ISSUE THREAD

**Issue by rockie667** [okgrow/meteor-image-upload#13]
I am currently trying to include meteor-image-upload to my first meteor project. So, sorry for some newbie questions...

I am using autoform and I am wondering how I can display the image upload button in an autoform. 

Secondly I would like to know how I set up the image field in the SimpleSchema for the collection where the image is appended, in my case it would be a schema for a products collection.

Thanks a lot for any help!
Hans

**Comment by pauldowman** [comment]
It doesn't explicitly support autoform, but I think it would still work in an autoform form. I'm not really sure. @benstr might know more.

**Comment by benstr** [comment]
@rockie667 you can include the imageUpload template partial (https://github.com/okgrow/meteor-image-upload#upload-image-template) inside the autoform block template.

```
{{#autoForm collection="Products" id="product-edit-form" type="update" doc=product}}
  {{> afQuickFields}}
  {{> uploadImage imageCollection="productImages" size="thumbnail" doc=product}}
  <button class="button" type="submit">Update Product</button>
{{/autoForm}}
```

As far as SimpleSchema: On the Products collection you do not need to store the image id anywhere on the product document since the image's document stores the product's id. We do it this way so you can have multiple images associated with one product and not worry about managing an array of image ids on the product doc. 

You can see a template helper example that grabs the associated image in our README: https://github.com/okgrow/meteor-image-upload#display-image

**Comment by rockie667** [comment]
Thank you very much, benstr!

But I get an error in

```
ProductImages = ImageUpload.createCollection("productImages", Products, {
    defaultPermissions: true,
    maxUploadSize: 30,
    sizes: {
        thumbnail: [200, 200],
        normal: [800,800],
        large: [1200, 1200]
    }
});
```

saying: Reference error: Products is not defined.

But the Products collection IS defined! Do you have an idea what I am missing?

Thank you very much!

**Comment by benstr** [comment]
@rockie667 that is a different issue that is not caused by ImageUpload. Check that `Products` is created before `ProductImages`. Currently your code must be structured in a way that creates `ProductImages` before.

To verify, move `ProductImages = ImageUpload.createCollection(...)` to the bottom of the same file that `Products = ImageUpload.createCollection(...)` is in.
