### ISSUE TITLE
Base64 image provided by Meteors camera

### ISSUE THREAD

**Issue by jlynch80** [okgrow/meteor-image-upload#8]
How would i go about using meteors default camera module, which provides the image as a base64 encoded image, and use that as the file to store to s3 instead of choosing from file input

**Comment by deanrad** [comment]
Good question - I know Meteor's internal [base64](https://atmospherejs.com/meteor/base64) has a method to do the decoding, but I imagine you're asking about how you tell the image upload package to use it, correct ?

**Comment by jlynch80** [comment]
Correct.

**Comment by pauldowman** [comment]
You can just use the default template that this package provides, I don't know of a reason to use the Cordova camera plugin. 

Technically this uses a file input which causes Cordova apps to let you use the camera or pick from the gallery (on devices that I have tested anyway). 

CollectionFS needs a file object, and you really don't want to just store Base64 encoded image data in a Mongo collection because even if it fits within the 16 MB limit you'll have performance problems. (Plus you'll only have the original large size which will cause further performance problems).

**Comment by benstr** [comment]
@jlynch80 I can confirm you do not need MDGs camera plugin in order for this package to work with Cordova. Just add this package and you are all set.

**Comment by benstr** [comment]
@jlynch80 we came across an issue with Crosswalk which we temporarily solved by using MDG's camera plugin with ImageUpload. You can see the snippet here: https://github.com/okgrow/meteor-image-upload/issues/12
